### ISSUE TITLE
code style

### ISSUE THREAD

**Issue by JAndrassy** [arduino-libraries/Arduino_10BASE_T1S#20]
Why the library and its examples don't use the Arduino code style?
https://docs.arduino.cc/learn/contributions/arduino-library-style-guide/

**Comment by aentinger** [comment]
Are there any specific elements that bother you?

**Comment by JAndrassy** [comment]
> Use camel case function names, not underscore. For example, analogRead, not analog_read. Or myNewFunction, not my_new_function. We've adopted this from Processing.org for readability's sake.

> Don’t assume knowledge of pointers. Beginning users of C find this the biggest roadblock, and get very confused by & and *, so whenever you can avoid having them hanging out in the API, do so.

**Comment by aentinger** [comment]
Unfortunately this library got released before a a final review on those elements happened - I'll go and adjust this where sensible.
